//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maerskline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int agentID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string agentFN { get; set; }
        public string agentLN { get; set; }
        public string agentEmail { get; set; }
        public string agentContact { get; set; }
    }
}
