//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maerskline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customerID { get; set; }
        public string customerFN { get; set; }
        public string customerLN { get; set; }
        public string gender { get; set; }
        public Nullable<int> age { get; set; }
    }
}
