//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maerskline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int staffID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string staffFN { get; set; }
        public string staffLN { get; set; }
        public string staffEmail { get; set; }
        public string staffContact { get; set; }
    }
}
